Few fixes
DanRohde/webdavcgi pull request #5
Opened 2019-03-17 21:28 UTC by noci2012

1) Ensure PATH_TRANSLATED ends in / for directories (webDAVCGI.pm)
2) type in style.css with a invalid reference for text-hover.

2019-03-18 08:49 UTC, DanRohde requested changes
Hi noci2012,
I cannot merge it because this works only with local filesystem backends. 
Can you send me a bug report with a good description of your problem? 
Thx,
Daniel

2019-03-18 08:57 UTC, DanRohde approved these changes

2019-03-18 08:58 UTC, DanRohde commented
i fixed the CSS typo in the ImageInfo extensions.

2019-03-18 08:58 UTC, closed without merging

2019-03-19 10:02 UTC, noci2012 commented
Issues are not enabled it seems: So here goed:

The issue is if directory paths are not ending in / then username + filename appear concatenated in the list.
The check if a terminating / is in the path cannot be done in the webserver due to ownership issues. 
So the change request is to ensure that a / is on every path leading to a directory.